/* this file is generated by scripts/load-token */
import { Network } from './const'
export enum AssetType { VET = 0, VTHO, 'PLA', 'SHA', 'EHrT', 'DBET', 'TIC', 'OCE', 'SNK', 'JUR', 'AQD', 'YEET', 'HAI', 'MDN', 'VEED', 'VPU', 'MVG', 'WoV', 'GEMS', 'VEX', 'VEUSD', 'VVET', 'DHN', 'UNION', 'VST', 'PPR', 'DRAGON', 'VSEA', 'BANANA', 'GOLD', 'LGCT', 'VFA', 'FCWS', 'MVC', 'MVA', '3DT', 'LION', 'SHT', 'SQUAD', 'BVC', 'USDV', 'VSC', 'Rain', 'MILK', 'PLG', 'EXO', 'UNO', 'GCRED', 'VEME', 'TVIRC', 'BANGZ', 'VOT3', 'B3TR'}
export interface Token {
    name: string
    address: string
    symbol: string
    decimals: number,
    genesis?: {
        [address: string]: string
    }
}
export const list:{ [index: string]: { [index: string]: Token } } = {
    "0x00000000851caf3cfdb6e899cf5958bfb1ac3413d346d43539627e6be7ec1b4a": {
        "PLA": {
            "name": "Plair",
            "symbol": "PLA",
            "address": "0x89827f7bb951fd8a56f8ef13c5bfee38522f2e1f",
            "decimals": 18
        },
        "SHA": {
            "name": "Safe Haven",
            "symbol": "SHA",
            "address": "0x5db3c8a942333f6468176a870db36eef120a34dc",
            "decimals": 18
        },
        "EHrT": {
            "name": "Eight Hours Token",
            "symbol": "EHrT",
            "address": "0xf8e1faa0367298b55f57ed17f7a2ff3f5f1d1628",
            "decimals": 18,
            "genesis": {
                "0x8d8d8a0c77628926908dedaf3fbffce3d416fc2d": "10000000000000000000000000000"
            }
        },
        "DBET": {
            "name": "Decent.bet",
            "symbol": "DBET",
            "address": "0x1b8ec6c2a45cca481da6f243df0d7a5744afc1f8",
            "decimals": 18,
            "genesis": {
                "0x1b8ec6c2a45cca481da6f243df0d7a5744afc1f8": "205903294831970956466297922"
            }
        },
        "TIC": {
            "name": "TicTalk",
            "symbol": "TIC",
            "address": "0xa94a33f776073423e163088a5078feac31373990",
            "decimals": 18
        },
        "OCE": {
            "name": "OceanEx",
            "symbol": "OCE",
            "address": "0x0ce6661b4ba86a0ea7ca2bd86a0de87b0b860f14",
            "decimals": 18
        },
        "SNK": {
            "name": "SneakerCoin",
            "symbol": "SNK",
            "address": "0x540768b909782c430cc321192e6c2322f77494ec",
            "decimals": 18
        },
        "JUR": {
            "name": "Jur",
            "symbol": "JUR",
            "address": "0x46209d5e5a49c1d403f4ee3a0a88c3a27e29e58d",
            "decimals": 18
        },
        "AQD": {
            "name": "Aqua Diamond Token",
            "symbol": "AQD",
            "address": "0xf9fc8681bec2c9f35d0dd2461d035e62d643659b",
            "decimals": 18
        },
        "YEET": {
            "name": "Yeet Coin",
            "symbol": "YEET",
            "address": "0xae4c53b120cba91a44832f875107cbc8fbee185c",
            "decimals": 18
        },
        "HAI": {
            "name": "HackenAI",
            "symbol": "HAI",
            "address": "0xacc280010b2ee0efc770bce34774376656d8ce14",
            "decimals": 8
        },
        "MDN": {
            "name": "Madini",
            "symbol": "MDN",
            "address": "0x1b44a9718e12031530604137f854160759677192",
            "decimals": 18
        },
        "VEED": {
            "name": "VIMworld",
            "symbol": "VEED",
            "address": "0x67fd63f6068962937ec81ab3ae3bf9871e524fc9",
            "decimals": 18,
            "genesis": {
                "0x1eb065a93bf325f53abc47c23289946bedec3d72": "100000000000000000000000000000"
            }
        },
        "VPU": {
            "name": "VPunks Token",
            "symbol": "VPU",
            "address": "0xb0821559723db89e0bd14fee81e13a3aae007e65",
            "decimals": 18
        },
        "MVG": {
            "name": "Mad Viking Games",
            "symbol": "MVG",
            "address": "0x99763494a7b545f983ee9fe02a3b5441c7ef1396",
            "decimals": 18
        },
        "WoV": {
            "name": "WorldOfV",
            "symbol": "WoV",
            "address": "0x170f4ba8e7acf6510f55db26047c83d13498af8a",
            "decimals": 18
        },
        "GEMS": {
            "name": "GEMS",
            "symbol": "GEMS",
            "address": "0x28c61940bdcf5a67158d00657e8c3989e112eb38",
            "decimals": 18
        },
        "VEX": {
            "name": "Vexchange",
            "symbol": "VEX",
            "address": "0x0bd802635eb9ceb3fcbe60470d2857b86841aab6",
            "decimals": 18
        },
        "VEUSD": {
            "name": "VeUSD",
            "symbol": "VEUSD",
            "address": "0x4e17357053da4b473e2daa2c65c2c949545724b8",
            "decimals": 6
        },
        "VVET": {
            "name": "Veiled VET",
            "symbol": "VVET",
            "address": "0x45429a2255e7248e57fce99e7239aed3f84b7a53",
            "decimals": 18
        },
        "DHN": {
            "name": "Dohrnii",
            "symbol": "DHN",
            "address": "0x8e57aadf0992afcc41f7843656c6c7129f738f7b",
            "decimals": 18
        },
        "UNION": {
            "name": "UNION token",
            "symbol": "UNION",
            "address": "0x34109fc2a649965eecd953d31802c67dcc183d57",
            "decimals": 18
        },
        "VST": {
            "name": "VeStacks",
            "symbol": "VST",
            "address": "0xb9c146507b77500a5cedfcf468da57ba46143e06",
            "decimals": 18
        },
        "PPR": {
            "name": "Paper Token",
            "symbol": "PPR",
            "address": "0x2f10726b240d7efb08671f4d5f0a442db6f29416",
            "decimals": 18
        },
        "DRAGON": {
            "name": "Dragon Coin",
            "symbol": "DRAGON",
            "address": "0x107a0b0faeb58c1fdef97f37f50e319833ad1b94",
            "decimals": 18
        },
        "VSEA": {
            "name": "VeSea Token",
            "symbol": "VSEA",
            "address": "0x23368c20c16f64ecbb30164a08666867be22f216",
            "decimals": 18
        },
        "BANANA": {
            "name": "BananaCoin",
            "symbol": "BANANA",
            "address": "0xf01069227b814f425bad4ba70ca30580f2297ae8",
            "decimals": 18
        },
        "GOLD": {
            "name": "GOLD Coin",
            "symbol": "GOLD",
            "address": "0xff3bc357600885aaa97506ea6e24fb21aba88fbd",
            "decimals": 18
        },
        "LGCT": {
            "name": "LEGACY TOKEN",
            "symbol": "LGCT",
            "address": "0xe5bb68318120828fd1159bf73d0e3a823043efc8",
            "decimals": 18
        },
        "VFA": {
            "name": "VFoxToken",
            "symbol": "VFA",
            "address": "0xa4f95b1f1c9f4cf984b0a003c4303e8ea86302f6",
            "decimals": 18
        },
        "FCWS": {
            "name": "FreeCoffeeWithSunny",
            "symbol": "FCWS",
            "address": "0xd5bd1b64cc9dafbfd58abd1d24a51f745ba64712",
            "decimals": 0
        },
        "MVC": {
            "name": "MyVeChain",
            "symbol": "MVC",
            "address": "0x02de9e580b51907a471d78ccfb2e8abe4c6b7515",
            "decimals": 18
        },
        "MVA": {
            "name": "MVA Token",
            "symbol": "MVA",
            "address": "0xc3fd50a056dc4025875fa164ced1524c93053f29",
            "decimals": 18
        },
        "SQUAD": {
            "name": "SQUAD",
            "symbol": "SQUAD",
            "address": "0xb27a1fb87935b85cdaa2e16468247278c74c5ec7",
            "decimals": 18
        },
        "3DT": {
            "name": "ThreeDAbleToken",
            "symbol": "3DT",
            "address": "0x8fcddbb322b18d8bdaec9243e9f4c6eb8901e566",
            "decimals": 18
        },
        "LION": {
            "name": "LION",
            "symbol": "LION",
            "address": "0x99ae6b435d37995befb749670c1fb7c377fbb6d1",
            "decimals": 18
        },
        "SHT": {
            "name": "Sh*tCoin",
            "symbol": "SHT",
            "address": "0x9af004570f2a301d99f2ce4554e564951ee48e3c",
            "decimals": 18
        },
        "BVC": {
            "name": "Black Ve Coin",
            "symbol": "BVC",
            "address": "0x7ae288b7224ad8740b2d4fc2b2c8a2392caea3c6",
            "decimals": 18
        },
        "VSC": {
            "name": "VSC",
            "symbol": "VSC",
            "address": "0x65c542ad413dd406d7ae5e47f61fbda027ce7983",
            "decimals": 18
        },
        "USDV": {
            "name": "Vyvo US Dollar",
            "symbol": "USDV",
            "address": "0x094042f9719cd6736fa3bd45b605b1b2a23abdec",
            "decimals": 6
        },
        "Rain": {
            "name": "Rainbow",
            "symbol": "Rain",
            "address": "0x3cb62f48dbdc4f7627f37f027811565d292a1001",
            "decimals": 18
        },
        "MILK": {
            "name": "MILK",
            "symbol": "MILK",
            "address": "0x64a8dea68772d478240dd6d3080a8e7f288a720f",
            "decimals": 18
        },
        "PLG": {
            "name": "PLUG",
            "symbol": "PLG",
            "address": "0xb0d5b68a96fab5f3047f6de6f9377a460db7e528",
            "decimals": 18
        },
        "EXO": {
            "name": "EXO Token",
            "symbol": "EXO",
            "address": "0x47921404147046177b8038720ac2d0b2776ee5bf",
            "decimals": 18
        },
        "UNO": {
            "name": "Uno",
            "symbol": "UNO",
            "address": "0xab644843eeab886a5ed3ea22066c6ee5190cfb81",
            "decimals": 18
        },
        "GCRED": {
            "name": "GCRED Token",
            "symbol": "GCRED",
            "address": "0x9fbf641fd303bfb294fa9d5393962806644825b4",
            "decimals": 18
        },
        "VEME": {
            "name": "Vemecoin",
            "symbol": "VEME",
            "address": "0x70a647c84ac1f492efd302e1af6d1ab8d20223a0",
            "decimals": 0
        },
        "BANGZ": {
            "name": "BANGZ",
            "symbol": "BANGZ",
            "address": "0x6e0b217380b45fd9992bafa91c08a92455ec647a",
            "decimals": 18
        }
    },
    "0x000000000b2bce3c70bc649a02749e8687721b09ed2e15997f466536b20bb127": {
        "PLA": {
            "name": "Plair",
            "symbol": "PLA",
            "address": "0x645d2019ed39e58db76af602317d177b53ba8b9d",
            "decimals": 18
        },
        "EHrT": {
            "name": "Eight Hours Token",
            "symbol": "EHrT",
            "address": "0xdeff1d52f3fbf551b3337b9a02f719cd21da956b",
            "decimals": 18,
            "genesis": {
                "0xb5d8da87b6a92cc37477048b4bcd7b8070c843a7": "10000000000000000000000000000"
            }
        },
        "DBET": {
            "name": "Decent.bet",
            "symbol": "DBET",
            "address": "0x510fcddc9424b1bbb328a574f45bfddb130e1f03",
            "decimals": 18,
            "genesis": {
                "0x510fcddc9424b1bbb328a574f45bfddb130e1f03": "205903294831970956466297922"
            }
        },
        "OCE": {
            "name": "OceanEx",
            "symbol": "OCE",
            "address": "0x9652aead889e8df7b5717ed984f147c132f85a69",
            "decimals": 18
        },
        "JUR": {
            "name": "Jur",
            "symbol": "JUR",
            "address": "0x602b7a4309b3412d269c6cdddad962c0b94494d8",
            "decimals": 18
        },
        "YEET": {
            "name": "Yeet Coin",
            "symbol": "YEET",
            "address": "0x32456c328f647f5b35757d38fe634868d9fe3808",
            "decimals": 18
        },
        "SNK": {
            "name": "SneakerCoin",
            "symbol": "SNK",
            "address": "0xe0d0402a948ab02af08938dad2a79669bdbe1c31",
            "decimals": 18
        },
        "SHA": {
            "name": "Safe Haven",
            "symbol": "SHA",
            "address": "0xa1bcfa20a82eca70a5af5420b11bc53a279024ec",
            "decimals": 18
        },
        "MDN": {
            "name": "Madini",
            "symbol": "MDN",
            "address": "0x4c76f2c483e0ec292c06d0a0d1440717ed0787c0",
            "decimals": 18
        },
        "VEED": {
            "name": "VIMworld",
            "symbol": "VEED",
            "address": "0xa39a4b2e23220305083e2e7c94c8950ef1e641c6",
            "decimals": 18,
            "genesis": {
                "0x9860a75e0b2746b4ee459483dd095206b761f9a6": "100000000000000000000000000000"
            }
        },
        "MVG": {
            "name": "Mad Viking Games",
            "symbol": "MVG",
            "address": "0x6e32a40481dc95c7495b48ee81e3d388a0f0eb77",
            "decimals": 18
        },
        "GEMS": {
            "name": "GEMS",
            "symbol": "GEMS",
            "address": "0x7b12cdd6dc20bac5a7c85924e4d29f84a3bc376f",
            "decimals": 18
        },
        "VEUSD": {
            "name": "VeUSD",
            "symbol": "VEUSD",
            "address": "0x033bbc923a9378600c6b52fa9aada608c4cc7ece",
            "decimals": 6
        },
        "TVIRC": {
            "name": "TestViracoins",
            "symbol": "TVIRC",
            "address": "0xf276fbde42c9eb4f9c4e1828cb7cd2383fd7ba27",
            "decimals": 18
        },
        "VVET": {
            "name": "Veiled VET",
            "symbol": "VVET",
            "address": "0x86fb5343bbecffc86185c023a2a6ccc76fc0afd8",
            "decimals": 18
        },
        "UNION": {
            "name": "UNION token",
            "symbol": "UNION",
            "address": "0xea283edcfdb17a8a7537f8a6a84c4bd1c21d608d",
            "decimals": 18
        },
        "VST": {
            "name": "VeStacks",
            "symbol": "VST",
            "address": "0x737a9a0022f515983b0a6415b9525c3e5a443e2f",
            "decimals": 18
        },
        "PPR": {
            "name": "Paper Token",
            "symbol": "PPR",
            "address": "0x947112fe4e2a71a3e37cdf41733d5a570df3ddaa",
            "decimals": 18
        },
        "DRAGON": {
            "name": "Dragon Coin",
            "symbol": "DRAGON",
            "address": "0x98ceed8ee645c2d964cc0dd4342c832d52aeeb13",
            "decimals": 18
        },
        "VPU": {
            "name": "VPunks Token",
            "symbol": "VPU",
            "address": "0x8c1d95e96b69941b1b81145d2f2a100e7d259880",
            "decimals": 18
        },
        "VSEA": {
            "name": "VeSea",
            "symbol": "VSEA",
            "address": "0x776b68c9f217385b0a4657296f6bf6c4b2600557",
            "decimals": 18
        },
        "BANANA": {
            "name": "BananaCoin",
            "symbol": "BANANA",
            "address": "0xca92f3d24c3f04c3ab7711f5a8981b48900d1baf",
            "decimals": 18
        },
        "LGCT": {
            "name": "LEGACY TOKEN",
            "symbol": "LGCT",
            "address": "0xcd06d669e2ee5d2da9906f121818a7331e23fba2",
            "decimals": 18
        },
        "VFA": {
            "name": "VFoxToken",
            "symbol": "VFA",
            "address": "0xd625f35dfcb0ecdb83dc6d71e33c8d53b825fc48",
            "decimals": 18
        },
        "MVA": {
            "name": "MVA Token",
            "symbol": "MVA",
            "address": "0x307bd9ebe9b8f1baa59731f18aecc999e8b33dea",
            "decimals": 18
        },
        "SQUAD": {
            "name": "SQUAD",
            "symbol": "SQUAD",
            "address": "0xcb384a3a82bfe0619963d65a05f3801ddc23f3cc",
            "decimals": 18
        },
        "3DT": {
            "name": "ThreeDAbleToken",
            "symbol": "3DT",
            "address": "0xa258e1a871f10cccf6330bfa06366d929ea26b46",
            "decimals": 18
        },
        "BVC": {
            "name": "Black Ve Coin",
            "symbol": "BVC",
            "address": "0x441ce74a5d456e3b262fc3d9f3b2c359f7d77016",
            "decimals": 18
        },
        "MILK": {
            "name": "MILK",
            "symbol": "MILK",
            "address": "0xbfbb567e5d734cffe510ab23d08f6c46f990c909",
            "decimals": 18
        },
        "GCRED": {
            "name": "GCRED Token",
            "symbol": "GCRED",
            "address": "0x810def6605aef9436059a60eda1382367966e9de",
            "decimals": 18
        },
        "BANGZ": {
            "name": "BANGZ",
            "symbol": "BANGZ",
            "address": "0xd105d3d218d36490590b474689b95dbe3bded6b7",
            "decimals": 18
        },
        "VOT3": {
            "name": "VOT3",
            "symbol": "VOT3",
            "address": "0x9df69ad8ff89063869e04164a11579c0a8532e84",
            "decimals": 18
        },
        "B3TR": {
            "name": "B3TR",
            "symbol": "B3TR",
            "address": "0xac0ca2a5148e15ef913f9f5cf8eb3cf763f5a43f",
            "decimals": 18
        }
    }
}
export const getToken = (net: Network, symbol: string) => {
    if (!list[net]) {
        throw new Error('unknown network: ' + net)
    }

    if (!list[net][symbol]) {
        throw new Error('unknown token: ' + symbol+ ' @'+ (net === Network.MainNet ? 'MainNet': 'TestNet'))
    }

    return list[net][symbol]
}
export const AssetConfig: {[index:string]:{type:number, decimals: number}} = {
    "VET": {
        "type": 0,
        "decimals": 18
    },
    "VTHO": {
        "type": 1,
        "decimals": 18
    },
    "PLA": {
        "type": 2,
        "decimals": 18
    },
    "SHA": {
        "type": 3,
        "decimals": 18
    },
    "EHrT": {
        "type": 4,
        "decimals": 18
    },
    "DBET": {
        "type": 5,
        "decimals": 18
    },
    "TIC": {
        "type": 6,
        "decimals": 18
    },
    "OCE": {
        "type": 7,
        "decimals": 18
    },
    "SNK": {
        "type": 8,
        "decimals": 18
    },
    "JUR": {
        "type": 9,
        "decimals": 18
    },
    "AQD": {
        "type": 10,
        "decimals": 18
    },
    "YEET": {
        "type": 11,
        "decimals": 18
    },
    "HAI": {
        "type": 12,
        "decimals": 8
    },
    "MDN": {
        "type": 13,
        "decimals": 18
    },
    "VEED": {
        "type": 14,
        "decimals": 18
    },
    "VPU": {
        "type": 15,
        "decimals": 18
    },
    "MVG": {
        "type": 16,
        "decimals": 18
    },
    "WoV": {
        "type": 17,
        "decimals": 18
    },
    "GEMS": {
        "type": 18,
        "decimals": 18
    },
    "VEX": {
        "type": 19,
        "decimals": 18
    },
    "VEUSD": {
        "type": 20,
        "decimals": 6
    },
    "VVET": {
        "type": 21,
        "decimals": 18
    },
    "DHN": {
        "type": 22,
        "decimals": 18
    },
    "UNION": {
        "type": 23,
        "decimals": 18
    },
    "VST": {
        "type": 24,
        "decimals": 18
    },
    "PPR": {
        "type": 25,
        "decimals": 18
    },
    "DRAGON": {
        "type": 26,
        "decimals": 18
    },
    "VSEA": {
        "type": 27,
        "decimals": 18
    },
    "BANANA": {
        "type": 28,
        "decimals": 18
    },
    "GOLD": {
        "type": 29,
        "decimals": 18
    },
    "LGCT": {
        "type": 30,
        "decimals": 18
    },
    "VFA": {
        "type": 31,
        "decimals": 18
    },
    "FCWS": {
        "type": 32,
        "decimals": 0
    },
    "MVC": {
        "type": 33,
        "decimals": 18
    },
    "MVA": {
        "type": 34,
        "decimals": 18
    },
    "3DT": {
        "type": 35,
        "decimals": 18
    },
    "LION": {
        "type": 36,
        "decimals": 18
    },
    "SHT": {
        "type": 37,
        "decimals": 18
    },
    "SQUAD": {
        "type": 38,
        "decimals": 18
    },
    "BVC": {
        "type": 39,
        "decimals": 18
    },
    "USDV": {
        "type": 40,
        "decimals": 6
    },
    "VSC": {
        "type": 41,
        "decimals": 18
    },
    "Rain": {
        "type": 42,
        "decimals": 18
    },
    "MILK": {
        "type": 43,
        "decimals": 18
    },
    "PLG": {
        "type": 44,
        "decimals": 18
    },
    "EXO": {
        "type": 45,
        "decimals": 18
    },
    "UNO": {
        "type": 46,
        "decimals": 18
    },
    "GCRED": {
        "type": 47,
        "decimals": 18
    },
    "VEME": {
        "type": 48,
        "decimals": 0
    },
    "TVIRC": {
        "type": 49,
        "decimals": 18
    },
    "BANGZ": {
        "type": 50,
        "decimals": 18
    },
    "VOT3": {
        "type": 51,
        "decimals": 18
    },
    "B3TR": {
        "type": 52,
        "decimals": 18
    }
}
export const updateTime = 1710085510254
